server:
  port: 9010

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

    discovery:
      enabled: true

# Eureka client configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG


# Auth Service URL configuration for JWT validation filter
auth:
  service:
    url: http://localhost:9002/loginWithLoginId  # Update this to your actual Auth service endpoint
