server:
  port: 9001
  servlet:
    context-path: /config-server

spring:
  application:
    name: config-server
  jmx:
    default-domain: config-server
  cloud:
    config:
      server:
        native:
           search-locations: classpath:/shared
  profiles:
    active: native
