spring:
  application:
    name: ticket-service

  profiles:
    active: main

server:
  port: 9021

---

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: main

  datasource:
    url: jdbc:oracle:thin:@10.43.50.201:1552/itmsuat
    username: AUTOSYS
    password: AUTOSYS_123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.Oracle12cDialect
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
