spring:
  application:
    name: ticket-service

  profiles:
    active: main

server:
  port: 9021

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

---

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: main
