spring:
  application:
    name: ticket-service

  profiles:
    active: main

server:
  port: 9021

---

spring:
  config:
    activate:
      on-profile: main

  main:
    allow-bean-definition-overriding: true

  # ===================== ORACLE CONFIG (COMMENTED) =====================
  # datasource:
  #   url: jdbc:oracle:thin:@10.43.50.201:1552/itmsuat
  #   username: AUTOSYS
  #   password: AUTOSYS_123
  #   driver-class-name: oracle.jdbc.OracleDriver
  #
  # jpa:
  #   hibernate:
  #     ddl-auto: none 
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true
  #       dialect: org.hibernate.dialect.OracleDialect
  #       physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  # =====================================================================

  # ===================== MYSQL CONFIG (ACTIVE) =====================
  datasource:
    url: jdbc:mysql://localhost:3306/itms_project
    username: root
    password: Mane@54321!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # =====================================================================

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.itms: DEBUG
