spring:
  application:
    name: ticket-service

  profiles:
    active: main

server:
  port: 9021

---

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
