spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itms_project
    username: root
    password: Mane@54321!
    driver-class-name: com.mysql.cj.jdbc.Driver

    tomcat:
      test-while-idle: true
      initial-size: 5
      max-total: 50
      max-idle: 20
      min-idle: 10
      max-wait: 20000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
