# General application configuration
spring:
  application:
    name: user-service

  profiles:
    active: main

server:
  port: 9002
  servlet:
    context-path: /user-service	
# Main profile-specific configuration
---
spring:
  config:
    activate:
      on-profile: main

  datasource:
    url: jdbc:mysql://localhost:3306/itms_project
    username: root
    password: Mane@54321!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # JWT configuration
  jwt:
    secret: verysecretkey1234567890!
    expiration: 300000            # 5 minutes in milliseconds
    refresh-expiration: 86400000  # 1 day in milliseconds

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
